

fruits:
    path: /
    controller: App\Controller\FruitsController::index
    methods: GET

add_favourite:
    path: /favourites/add
    controller: App\Controller\FruitsController::addFavourite
    methods: GET|POST

favourites:
    path: /favourites
    controller: App\Controller\FavouriteController::index
    methods: GET
